### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by bert1973** [mnf71/udr-nanodbc#3]
Hi,

Do you have any numbers/ experience about performance?
Is using the nanoodbc udr way faster than a standalone tool that opens an odbc connection combined with:

1. An embedded FB connection, and uses a prepared statement for insert?
2. Or even use the new batch insert operation in the FB 4.0 api?

Kind regards,
Bert

**Comment by mnf71** [comment]
Hi,

What is your goal? 
If you transfer data from Firebird to Firebird, then it is better to use ON EXTERNAL DATA SOURCE. 
UDR slower for it. 

Maxim

**Comment by bert1973** [comment]
I would like to pump data from an InterBase database to a Firebird database.
So ON EXTERNAL DATA SOURCE woudn't work unfortunately.

**Comment by mnf71** [comment]
Hmm, 

Interbase + 
-Driver (?) - app (?) - embeded FB DML 
vs 
-ODBC-nanoUDR-get data-stored procedure 

This should be checked. At first glance, the UDR could be faster... need test. 

Maxim

**Comment by mnf71** [comment]
Bert,

Did a little test to let you know how it UDR works, a Firebird cursor and outer a UDR cursor. Worse by about 10 times... Compare with these results and metadata for your application and DB to do conclude that be better UDR or embeded FB.  
https://github.com/mnf71/udr-nanodbc/tree/master/test 
With 1 byte codepage (not UTF8) will faster

Platform:
https://shop.lenovo.ru/product/10MLS3GX00/
HDD ST500DM002

Database: 

gstat version WI-V3.0.6.33328 Firebird 3.0

Database "C:\DB\.FDB\LOG$.FDB"
Gstat execution time Tue Dec 28 17:46:33 2021

Database header page information:
        Flags                   0
        Generation              55062
        System Change Number    0
        Page size               16384
        ODS version             12.0
        Oldest transaction      54426
        Oldest active           54427
        Oldest snapshot         54427
        Next transaction        54448
        Sequence number         0
        Next attachment ID      5387
        Implementation          HW=AMD/Intel/x64 little-endian OS=Windows CC=MSVC
        Shadow count            0
        Page buffers            4096
        Next header page        0
        Database dialect        1
        Creation date           Aug 29, 2020 10:01:19
        Sweep interval:         0

Maxim

**Comment by mnf71** [comment]
Conducted tests with measurements of function calls: simple, context, etc. As a result, I came to the conclusion to avoid the overhead of copying to write pumped-functions for such tasks...

possible implementation 

pump in :

```sql
  FUNCTION pump (
      rslt TY$POINTER NOT NULL, -- recordset
      query VARCHAR(8191) CHARACTER SET UTF8 NOT NULL, -- insert, merge and etc
      tnx_gap INTEGER NOT NULL DEFAULT 0, -- != 0, commit internal transaction via pumped gap, otherwise common transaction
    ) RETURNS TY$NANO_BLANK;
```
pump out:

?

**Comment by mnf71** [comment]
Added a pump function to improve the performance of uploading data into FB database. 
PERF_PUMP vs PERF_PUMP_2 (7m 23s 234ms vs 4m 42s 344ms) minus ~35% 

Best regards,
Maxim

**Comment by mnf71** [comment]
Closed
